### ISSUE TITLE
Error on launch in 0.0.8

### ISSUE THREAD

**Issue by rnewman** [mozilla/datomish-user-agent-service#29]
With a new DB:

```
Opening Datomish knowledge-base at /Users/rnewman/Library/Application Support/Tofino-dev/browser-datomish.db
unhandledRejection at: Promise {}
unhandledRejection Error: Invalid value for attribute 1, expected :db.type/keyword but got 29
    at Error (native)
    at new $cljs$core$ExceptionInfo$$ (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:10827:19)
    at $cljs$core$ex_info$cljs$0core$0IFn$0_invoke$0arity$02$$ (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:10853:10)
    at $datomish$schema$ensure_valid_value$$ (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:18421:13)
    at /Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:24293:462
    at $db$$131$$ (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:24216:55)
    at $c__32359__auto___65483$$ (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:24246:37)
    at $cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped$$ (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:11519:27)
    at /Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:24303:14
    at Immediate.$cljs$core$async$impl$dispatch$process_messages$$ [as _onImmediate] (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:11240:135)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

with an existing DB (looks like a `null` somewhere):

```
Started Datomish User Agent Service.
Listening at http://localhost:9090/v1
Accepting CORS requests from tofino://
Opening Datomish knowledge-base at /Users/rnewman/Library/Application Support/Tofino-dev/browser-datomish.db
uncaughtException TypeError: Cannot read property '$cljs$core$async$impl$protocols$Channel$close_BANG_$arity$1$' of null
    at $cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped$$ (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:11521:56)
    at /Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:11528:12
    at /Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:11341:147
    at Immediate.$cljs$core$async$impl$dispatch$process_messages$$ [as _onImmediate] (/Users/rnewman/moz/git/tofino/lib/node_modules/datomish-user-agent-service/target/release-node/datomish_user_agent_service.js:11240:135)
    at tryOnImmediate (timers.js:543:15)
```

**Comment by rnewman** [comment]
Fixed in 0.0.10.
